### ISSUE TITLE
Vectorize the new logo

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy.github.io.src#1]
Maybe: https://inkscape.org/doc/tracing/tutorial-tracing.html

![pydy-potato](https://cloud.githubusercontent.com/assets/276007/6094753/b90e10e6-aeed-11e4-8396-9576f3904ee1.jpg)

**Comment by moorepants** [comment]
Yumi and I are giving a go at this but anyone else is welcome to try too.

**Comment by moorepants** [comment]
@pydy/pydy-developers 

Here is a first shot at vectorizing. Let me know what you all think, then I'll tweak, and submit to the repository.

![pydy-potato-vectorized](https://cloud.githubusercontent.com/assets/276007/6099565/a4268f1e-afb0-11e4-8cd4-e6a8eb398288.png)

**Comment by moorepants** [comment]
@monthubbard Thought you might like to see our logo.

**Comment by chrisdembia** [comment]
Beautiful! I like it a lot. Only thing is that the lower right corner looks like a frowny face.

**Comment by moorepants** [comment]
The logo is in. We can iterate on it to improve later. Now we have something to start with.
