### ISSUE TITLE
The responisive design needs some work.

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy.github.io.src#17]
The logo doesn't work with the responsive design and the side bars are placed above the intro:
![pydy multibody dynamics with python pydy website - mozilla firefox_060](https://cloud.githubusercontent.com/assets/276007/6658607/f6a97fa8-cb2b-11e4-9faa-cc462299b3ac.png)

**Comment by moorepants** [comment]
@sahilshekhawat

**Comment by sahilshekhawat** [comment]
updated responsive design
![pydywebsite](https://cloud.githubusercontent.com/assets/5890452/6666147/8067a3a6-cc07-11e4-96e6-5ec2d142aeb7.png)
