### ISSUE TITLE
Logo too small 

### ISSUE THREAD

**Issue by chrisdembia** [pydy/pydy.github.io.src#18]
The logo is kinda small; can we make it bigger?

**Comment by moorepants** [comment]
I agree, but one problem is our design. The words PyDy are small relative to the potato and snake. So to make the words more readable the logo has to be big.

**Comment by chrisdembia** [comment]
![image](https://cloud.githubusercontent.com/assets/846001/6660558/8371e736-cb59-11e4-88d5-e6d58e30afa0.png)

**Comment by chrisdembia** [comment]
BTW that's using Chrome.

**Comment by moorepants** [comment]
Interesting. That's different than what I see.
Firefox:
![pydy multibody dynamics with python pydy website - mozilla firefox_061](https://cloud.githubusercontent.com/assets/276007/6660947/7fd97d8e-cb61-11e4-8390-7f512628b028.png)

**Comment by moorepants** [comment]
Chromium for me:
![pydy multibody dynamics with python pydy website - chromium_062](https://cloud.githubusercontent.com/assets/276007/6660995/12e582b2-cb62-11e4-8ef2-e7b3c42ab3a2.png)

**Comment by sahilshekhawat** [comment]
Sorry about that, that is supposed to be a responsive feature, rather than a bug. Fixing
