### ISSUE TITLE
Customize the theme so it isn't so obviously a Bootstrap based website!

### ISSUE THREAD

**Issue by moorepants** [pydy/pydy.github.io.src#5]

**Comment by moorepants** [comment]
@tarzzz Are you willing to work on this further? It would be nice if our theme looked more unique and had a place for the new logo, #1.

**Comment by moorepants** [comment]
@tarzzz Here is a nice site @oliverlee found: http://quant-econ.net/

Could be good to mimic or get ideas from.

**Comment by tarzzz** [comment]
I am looking into it. Will try to come up with some design in a day or two.
:)

**Comment by moorepants** [comment]
Great, thanks.

**Comment by moorepants** [comment]
@tarzzz Just came across these: http://html5up.net/

They aren't bootstrap based, but freely licensed and look nice. Maybe they are useful.

**Comment by tarzzz** [comment]
Yep, They look awesome. Maybe i can look into them. We can use them in our
custom layout.html

**Comment by moorepants** [comment]
Fixed in #16
